---
  - name: LogWatch | Install base packages
    apt:
      pkg:
       - logwatch
    become: yes
    tags:
      - logwatch

  - name: LogWatch | Patch /usr/share/logwatch/default.conf/logwatch.conf - default properties
    lineinfile:
      dest: /usr/share/logwatch/default.conf/logwatch.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: "{{ item.insertafter | default('EOF') }}"
    with_items: "{{ logwatch_conf_default_props | default([]) }}"
    become: yes
    tags:
      - logwatch

  - name: LogWatch | Patch /usr/share/logwatch/default.conf/logwatch.conf - custom properties
    lineinfile:
      dest: /usr/share/logwatch/default.conf/logwatch.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      insertafter: "{{ item.insertafter | default('EOF') }}"
    with_items: "{{ logwatch_conf_props | default([]) }}"
    become: yes
    tags:
      - logwatch

  - name: Logwatch | Remove logwatch's default cronjob
    file: path=/etc/cron.daily/00logwatch state=absent
    become: yes
    tags:
      - logwatch

  - name: Logwatch | Configure logwatch's cronjob
    cron: name=logwatch job="/usr/sbin/logwatch --output mail" special_time="{{ logwatch_cron_time | default('daily') }}"
    when: option_setup_cron
    become: yes
    tags:
      - logwatch

